import { Agent } from "@mastra/core/agent";
import { openai } from "@ai-sdk/openai";
import { blogWritingTool } from "../tools/blogWritingTool";

export const writerAgent = new Agent({
  name: "Writer Assistant",
  instructions: `You are a professional blog publisher. Your role is to:
    1. Take the blog content generated by the blog writing tool
    2. don't modify the content, keep it as it is 
    Do not modify the content, only print it as it is.`,
  model: openai("gpt-4o-mini"),
  tools: {
    blogWritingTool,
  },
});
