import { Mastra } from "@mastra/core";
import { Agent } from "@mastra/core/agent";
import { createTool } from "@mastra/core/tools";
import { openai } from "@ai-sdk/openai";
import { z } from "zod";
import OpenAI from 'openai';

const apiKey = process.env.NEBIUS_API_KEY;
const client = new OpenAI({
    baseURL: "https://api.studio.nebius.ai/v1/",
    apiKey: apiKey,
});

const blogWritingTool = createTool({
  id: "Write a Blog Article",
  inputSchema: z.object({
    topic: z.string().describe("The topic to write a blog post about"),
  }),
  description: `Generates a well-crafted blog post about the specified topic`,
  execute: async ({ context: { topic } }) => {
    const response = await client.chat.completions.create({
      model: "Qwen/Qwen3-235B-A22B",
      temperature: 0.7,
      top_p: 0.95,
      messages: [
        {
          role: "system",
          content: "You are a professional blog writer. Create a beautifully crafted blog post that is engaging, informative, and well-structured. Focus solely on the given topic and provide valuable insights."
        },
        {
          role: "user",
          content: `Write a comprehensive blog post about: ${topic}`
        }
      ]
    });

    return { 
      blogContent: response.choices[0].message.content
    };
  },
});

const writerAgent = new Agent({
  name: "Writer Assistant",
  instructions: `You are a professional blog publisher. Your role is to:
    1. Take the blog content generated by the blog writing tool
    2. Don't modify the content, keep it as it is 
    Do not modify the content, only print it as it is.
    Use the blogWritingTool to generate the blog content based on the topic provided by the user. Pass that to the tool.`,
  model: openai("gpt-4o-mini"),
  tools: {
    blogWritingTool,
  },
});

export const mastra = new Mastra({
  agents: { writerAgent },
});

// Example usage
async function main() {
  const agent = await mastra.getAgent("writerAgent");
  const result = await agent.generate("Write a blog post about artificial intelligence in healthcare");
  console.log(result.text);
}

// Uncomment to run the example
// main();